---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ${VAGRANT_DEFAULT_BOX:-generic/rhel7}
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8080, host: 10080"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
  inventory:
    host_vars:
      instance:
        environment: vagrant
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
