---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl


    # Role: java
    java_home: /usr/lib/jvm/java-1.8.0-openjdk.x86_64

    # Ansible Role: Postgres
    use_scl: true
    postgresql_databases:
      - name: example
      - name: fcrepo
    postgresql_users:
      - name: fcrepo
        password: fcrepo
    postgresql_hba_entries:
      - {type: local, database: all, user: postgres, auth_method: peer}
      - {type: local, database: all, user: all, auth_method: peer}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
      - {type: host, database: fcrepo, user: fcrepo, address: '127.0.0.1/32', auth_method: md5}

    # Role: tomcat
    tomcat_java_home: /usr/lib/jvm/java-1.8.0-openjdk.x86_64
    tomcat_heap_min: "128m"
    tomcat_heap_max: "128m"
    tomcat_max_perm_size: "128m"
    tomcat_java_opts:
      - -Dfcrepo.modeshape.configuration=file:{{ fcrepo_config_dir }}/repository.json
      - -Dfcrepo.home={{ fcrepo_home_dir }}
  
  roles:
    - role: nycrecords.rhsm
    - role: nycrecords.postgresql
    - role: nycrecords.java
    - role: nycrecords.tomcat
    - role: ansible-role-fcrepo